### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by amidesfahani** [php-monsters/laravel-online-payment#24]
Hi
`
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'extra_params' can't have a default value
`

to fix this mysql issue just delete "->default('{}')" from "jsonb" columns.

- Laravel 7
- Windows 10
- WampServer 3.2.0 64bit

**Comment by amidesfahani** [comment]
Still exists

```
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'extra_params' can't have a default value (SQL: create table `larapay_transactions` (`id` int unsigned not null auto_increment primary key, `model_type` varchar(191) not null, `model_id` bigint unsigned not null, `accomplished` tinyint(1) not null default '0', `verified` tinyint(1) not null default '0', `after_verified` tinyint(1) not null default '0', `reversed` tinyint(1) not null default '0', `submitted` tinyint(1) not null default '0', `approved` tinyint(1) not null default '0', `rejected` tinyint(1) not null default '0', `payment_method` varchar(255) not null default 'ONLINE', `bank_order_id` varchar(20) null, `gate_name` varchar(20) null, `gate_refid` varchar(40) null, `gate_status` varchar(191) null, `description` text null, `amount` bigint not null default '0', `extra_params` json null default '{}', `additional_data` json null default '{}', `sharing` json null default '{}', `paid_at` datetime null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)
```

- Laravel 8

**Comment by rahx** [comment]
Hello @amidesfahani, the issue you have encountered isn't from laravel o the package it is from your mysql version and you want to escape it you have to edit mysql config file, I wish this help:

https://stackoverflow.com/questions/38433603/mysql2error-blob-text-geometry-or-json-column-body-cant-have-a-default-v

If you copy and paste the code below in your mysql, you will see the problem is from there:

create table `larapay_transactions` (`id` int unsigned not null auto_increment primary key, `model_type` varchar(191) not null, `model_id` bigint unsigned not null, `accomplished` tinyint(1) not null default '0', `verified` tinyint(1) not null default '0', `after_verified` tinyint(1) not null default '0', `reversed` tinyint(1) not null default '0', `submitted` tinyint(1) not null default '0', `approved` tinyint(1) not null default '0', `rejected` tinyint(1) not null default '0', `payment_method` varchar(255) not null default 'ONLINE', `bank_order_id` varchar(20) null, `gate_name` varchar(20) null, `gate_refid` varchar(40) null, `gate_status` varchar(191) null, `description` text null, `amount` bigint not null default '0', `extra_params` json not null default '{}', `additional_data` json not null default '{}', `sharing` json not null default '{}', `paid_at` datetime null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'

**Comment by iamtartan** [comment]
You can change your migration file in this way too:
```php

if (env('DB_CONNECTION') == 'pgsql') { // for POSTGRESQL
    $table->jsonb('extra_params')->nullable()->default('{}');
    $table->jsonb('additional_data')->nullable()->default('{}');
    $table->jsonb('sharing')->nullable()->default('{}');
} else { // for MYSQL
    $table->jsonb('extra_params')->nullable();
    $table->jsonb('additional_data')->nullable();
    $table->jsonb('sharing')->nullable();
}
```

**Comment by arashrahimi46** [comment]
> You can change your migration file in this way too:
> 
> ```
> if (env('DB_CONNECTION') == 'pgsql') { // for POSTGRESQL
>     $table->jsonb('extra_params')->nullable()->default('{}');
>     $table->jsonb('additional_data')->nullable()->default('{}');
>     $table->jsonb('sharing')->nullable()->default('{}');
> } else { // for MYSQL
>     $table->jsonb('extra_params')->nullable();
>     $table->jsonb('additional_data')->nullable();
>     $table->jsonb('sharing')->nullable();
> }
> ```

Worked for me thanks
